services:
  - type: web
    name: the-broken-wood
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DASHBOARD_URL
        sync: false
