export const COLD_TRANSFER_TRIGGERS = {
  primary: [
    'you transferred me',
    'someone transferred me',
    'I was transferred',
    'you called me',
    'someone called me',
    "I didn't call you",
    "I didn't call this number",
    'stop calling me',
    'remove me from your list',
    'take me off your list',
    "I'm on the do not call list",
    'why are you calling me',
    'how did you get my number',
    'I never requested this',
    "I didn't ask for a quote",
    "I didn't fill out a form",
    'someone else called me',
    'a lady called me',
    'a guy called me',
    'a representative called',
    'you guys called me earlier',
    'I got a call from you',
    'I received a call',
    'put me back to the person',
    'transfer me back',
    'I want to talk to the first person',
    "where's the other person",
    'who was I talking to',
    'I was speaking to someone else',
    'who transferred me',
    'I was on the phone with someone',
    'the other person hung up',
    'why was I transferred',
    'I was already talking to someone',
    'the first person I spoke to',
    'they called me first',
    'I was cold transferred',
    'nobody told me about this transfer',
    'I did not consent to this call',
    'this is an unsolicited call',
    'you are calling me out of nowhere',
    'I never gave my number',
    'how did you get my information',
  ],
  secondary: [
    'what company is this',
    'who are you people',
    'I have no idea why I am on this call',
    'this is a scam',
    'are you a scammer',
    'I am going to report you',
    'I will call the police',
    'do not call me again',
    'this is harassment',
    'leave me alone',
  ],
};

export const CAMPAIGN_DURATION_THRESHOLDS: Record<string, number> = {
  'auto insurance': 120,
  'home insurance': 120,
  'solar': 120,
  'home improvement': 120,
  'plumbing': 120,
  'roofing': 120,
  'bathroom remodel': 120,
  'pest control': 120,
  'medicare': 300,
  default: 90,
};

export const HIGH_SENSITIVITY_CONFIDENCE_THRESHOLD = 30;
export const NORMAL_CONFIDENCE_THRESHOLD = 50;
