import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const campaigns = [
  // ==================== INBOUND CAMPAIGNS ====================
  {
    name: 'Roofing Inbounds',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls',
    description: 'High-intent roofing installation calls from homeowners seeking new roof installations.',
    payout: 68.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 125,
    geographic_focus: '20K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'New installations only (no repairs). Caller must be a homeowner. Hours: 8am-8pm EST Mon-Fri.',
    compliance_notes: 'Daily cap: 10 calls (testing phase). No concurrent call cap.',
    sort_order: 1,
  },
  {
    name: 'Pest Control Inbounds',
    industry: 'Home Services',
    call_type: 'Inbound Calls',
    description: 'Pest control service calls from consumers actively seeking pest removal solutions.',
    payout: 32.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Pest control only — no wildlife removal. Hours: 5am-11pm MST Mon-Sun.',
    compliance_notes: 'Daily cap: 10 calls (testing phase). No concurrent call cap.',
    sort_order: 2,
  },
  {
    name: 'Flooring Inbounds',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls',
    description: 'Flooring installation calls from homeowners looking for new floor installations.',
    payout: 45.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: '16K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'New installations only (no repairs). Must be a homeowner. Returns for keypress 2 (customer service). Hours: Mon-Fri 4:30am-10:30pm EST, Sat-Sun 4:30am-9:30pm EST.',
    compliance_notes: 'Daily cap: 10 calls (testing phase). Concurrent call cap: 3.',
    sort_order: 3,
  },
  {
    name: 'Gutters Inbounds',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls',
    description: 'Gutter installation calls from homeowners seeking new gutter systems.',
    payout: 50.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 140,
    geographic_focus: '36K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Gutter installation only. Hours: 7am-7pm CST Mon-Fri.',
    compliance_notes: 'Daily cap: 10 calls. No concurrent call cap.',
    sort_order: 4,
  },
  {
    name: 'Plumbing Inbounds',
    industry: 'Home Services',
    call_type: 'Inbound Calls',
    description: 'Plumbing service calls from consumers needing plumbing repairs or installations.',
    payout: 22.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 125,
    geographic_focus: '3.8K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Hours: 8am-7pm EST/PST Mon-Sun.',
    compliance_notes: 'No daily or concurrent call caps.',
    sort_order: 5,
  },
  {
    name: 'HVAC Inbounds',
    industry: 'Home Services',
    call_type: 'Inbound Calls',
    description: 'HVAC service calls from consumers seeking heating, ventilation, and AC services.',
    payout: 30.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 125,
    geographic_focus: '6.4K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Hours: 8am-8pm EST Mon-Sun.',
    compliance_notes: 'No daily or concurrent call caps.',
    sort_order: 6,
  },

  // ==================== TRANSFER CAMPAIGNS ====================
  {
    name: 'Roofing Transfers',
    industry: 'Home Improvement',
    call_type: 'Live Transfers',
    description: 'Live transferred roofing installation calls. Caller is warm-transferred to buyer after qualifying.',
    payout: 50.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 135,
    geographic_focus: '8.2K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Hours: 8am-10pm EST Mon-Fri, 10am-4pm EST Sat.',
    compliance_notes: 'No daily or concurrent call caps.',
    sort_order: 10,
  },
  {
    name: 'Bathroom Remodeling Transfers',
    industry: 'Home Improvement',
    call_type: 'Live Transfers',
    description: 'Live transferred bathroom remodeling calls from homeowners seeking bathroom renovations.',
    payout: 60.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 185,
    geographic_focus: '13.6K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Hours: 8am-10pm EST Mon-Fri, 10am-4pm EST Sat.',
    compliance_notes: 'No daily or concurrent call caps.',
    sort_order: 11,
  },
  {
    name: 'Window Installation Transfers',
    industry: 'Home Improvement',
    call_type: 'Live Transfers',
    description: 'Live transferred window installation calls from homeowners looking for new window replacements.',
    payout: 65.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 185,
    geographic_focus: '7.4K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Hours: 8am-10pm EST Mon-Fri, 10am-4pm EST Sat.',
    compliance_notes: 'No daily or concurrent call caps.',
    sort_order: 12,
  },
  {
    name: 'Plumbing Transfers',
    industry: 'Home Services',
    call_type: 'Live Transfers',
    description: 'Live transferred plumbing service calls from consumers needing plumbing work.',
    payout: 40.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 135,
    geographic_focus: '7.1K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Hours: 8am-10pm EST Mon-Fri, 10am-4pm EST Sat.',
    compliance_notes: 'No daily or concurrent call caps.',
    sort_order: 13,
  },
  {
    name: 'HVAC Transfers',
    industry: 'Home Services',
    call_type: 'Live Transfers',
    description: 'Live transferred HVAC service calls from consumers seeking heating and cooling services.',
    payout: 42.00,
    payout_type: 'per_conversion',
    billing_cycle: 'monthly_net14',
    min_duration: 145,
    geographic_focus: '6.5K targeted zip codes',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'Hours: 8am-10pm EST Mon-Fri, 10am-4pm EST Sat.',
    compliance_notes: 'No daily or concurrent call caps.',
    sort_order: 14,
  },

  // ==================== RTB CAMPAIGNS (Real Time Bidding) ====================
  // National + 24/7, payout varies by buyer bid
  {
    name: 'RTB — Appliance Repair',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding appliance repair calls. Multiple buyers compete — highest bidder wins. Payout range: $5-$30 depending on buyer bid.',
    payout: 5.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($5-$30). 24/7 availability.',
    sort_order: 20,
  },
  {
    name: 'RTB — Bathroom Remodeling',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding bathroom remodeling calls. Payout range: $30-$120 depending on buyer bid.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($30-$120). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 21,
  },
  {
    name: 'RTB — Electricians',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding electrician service calls. Payout range: $20-$80.',
    payout: 20.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($20-$80). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 22,
  },
  {
    name: 'RTB — Flooring',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding flooring installation calls. Payout range: $30-$100.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($30-$100). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 23,
  },
  {
    name: 'RTB — Gutters',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding gutter installation calls. Payout range: $30-$100.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($30-$100). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 24,
  },
  {
    name: 'RTB — Garage Doors',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding garage door service calls. New campaign — payout varies by buyer bid.',
    payout: 15.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid. GrovLabs takes 15% of payout. 24/7 availability. NEW campaign.',
    sort_order: 25,
  },
  {
    name: 'RTB — HVAC',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding HVAC service calls. Payout range: $40-$200.',
    payout: 40.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($40-$200). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 26,
  },
  {
    name: 'RTB — Kitchen Remodeling',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding kitchen remodeling calls. Payout varies by buyer bid.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid. GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 27,
  },
  {
    name: 'RTB — Landscaping',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding landscaping service calls. New campaign — payout varies by buyer bid.',
    payout: 15.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid. GrovLabs takes 15% of payout. 24/7 availability. NEW campaign.',
    sort_order: 28,
  },
  {
    name: 'RTB — Lawn Care',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding lawn care service calls. New campaign — payout varies by buyer bid.',
    payout: 10.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid. GrovLabs takes 15% of payout. 24/7 availability. NEW campaign.',
    sort_order: 29,
  },
  {
    name: 'RTB — Locksmith',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding locksmith service calls. Payout range: $5-$30.',
    payout: 5.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($5-$30). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 30,
  },
  {
    name: 'RTB — Mold Removal',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding mold removal calls. Payout range: $40-$150.',
    payout: 40.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($40-$150). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 31,
  },
  {
    name: 'RTB — Pest Control',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding pest control calls. Payout range: $20-$70.',
    payout: 20.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($20-$70). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 32,
  },
  {
    name: 'RTB — Plumbing',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding plumbing service calls. Payout range: $30-$200.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($30-$200). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 33,
  },
  {
    name: 'RTB — Roofing',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding roofing calls. Payout range: $30-$175.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($30-$175). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 34,
  },
  {
    name: 'RTB — Siding',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding siding installation calls. New campaign — payout varies by buyer bid.',
    payout: 20.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid. GrovLabs takes 15% of payout. 24/7 availability. NEW campaign.',
    sort_order: 35,
  },
  {
    name: 'RTB — Solar',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding solar installation calls. Payout range: $20-$50.',
    payout: 20.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($20-$50). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 36,
  },
  {
    name: 'RTB — Walk-In Tub',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding walk-in tub installation calls. New campaign — payout varies by buyer bid.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid. GrovLabs takes 15% of payout. 24/7 availability. NEW campaign.',
    sort_order: 37,
  },
  {
    name: 'RTB — Water Damage',
    industry: 'Home Services',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding water damage restoration calls. Payout range: $150-$600.',
    payout: 150.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($150-$600). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 38,
  },
  {
    name: 'RTB — Windows',
    industry: 'Home Improvement',
    call_type: 'Inbound Calls (RTB)',
    description: 'Real-time bidding window installation calls. Payout range: $30-$80.',
    payout: 30.00,
    payout_type: 'per_call',
    billing_cycle: 'monthly_net14',
    min_duration: 120,
    geographic_focus: 'Nationwide',
    allowed_traffic: 'All compliant traffic sources',
    restricted_traffic: 'Robocalls, Cold Transfers, Auto-dialers, Pre-recorded messages, Incentivized traffic',
    requirements: 'RTB: Payout varies by real-time buyer bid ($30-$80). GrovLabs takes 15% of payout. 24/7 availability.',
    sort_order: 39,
  },
];

async function main() {
  console.log('Seeding campaigns...');
  
  for (const c of campaigns) {
    await prisma.campaign.upsert({
      where: { name: c.name },
      update: { ...c },
      create: { ...c },
    });
    console.log(`  ✓ ${c.name}`);
  }

  const count = await prisma.campaign.count();
  console.log(`\nDone. ${count} campaigns in database.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
